server:
  port: 9021

spring:
  # elasticsearch
  elasticsearch:
    uris:
      - http://127.0.0.1:9200
    username: elastic
    password: laokou123
    connection-timeout: 30s
    socket-timeout: 30s